name: Build & publish Docker image

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract version from tag
        id: extract_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Get commit author info
        id: author
        run: |
          AUTHOR_NAME=$(git log -1 --format='%an' ${{ github.sha }})
          AUTHOR_EMAIL=$(git log -1 --format='%ae' ${{ github.sha }})
          echo "name=$AUTHOR_NAME" >> $GITHUB_OUTPUT
          echo "email=$AUTHOR_EMAIL" >> $GITHUB_OUTPUT

      - name: Update package.json version
        run: |
          jq --indent 1 '.version = "${{ steps.extract_version.outputs.VERSION }}"' package.json > package.json.tmp
          mv package.json.tmp package.json

      - name: Commit package.json changes
        run: |
          git config --local user.email "${{ steps.author.outputs.email }}"
          git config --local user.name "${{ steps.author.outputs.name }}"
          git add package.json
          git commit -m "chore: update version to ${{ steps.extract_version.outputs.VERSION }}"
          git push origin HEAD:master

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}
            ${{ secrets.DOCKERHUB_USERNAME }}/mongonaut
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value=latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max